# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotterMainWindow(object):
    def setupUi(self, PlotterMainWindow):
        PlotterMainWindow.setObjectName("PlotterMainWindow")
        PlotterMainWindow.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotterMainWindow.sizePolicy().hasHeightForWidth())
        PlotterMainWindow.setSizePolicy(sizePolicy)
        PlotterMainWindow.setMinimumSize(QtCore.QSize(800, 400))
        font = QtGui.QFont()
        font.setFamily("OpenSansEmoji")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        PlotterMainWindow.setFont(font)
        PlotterMainWindow.setStyleSheet("font: 12pt \"OpenSansEmoji\";")
        self.centralwidget = QtWidgets.QWidget(PlotterMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setMinimumSize(QtCore.QSize(100, 30))
        self.tab_widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tab_widget.setStyleSheet("border-bottom: 1px solid #ddd;")
        self.tab_widget.setObjectName("tab_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_widget)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_page_button = QtWidgets.QPushButton(self.tab_widget)
        self.add_page_button.setMinimumSize(QtCore.QSize(35, 30))
        self.add_page_button.setMaximumSize(QtCore.QSize(25, 30))
        self.add_page_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_page_button.setStyleSheet("QPushButton {\n"
"    border: 1px solid #ccc;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    background: #eee;\n"
"}")
        self.add_page_button.setObjectName("add_page_button")
        self.horizontalLayout_2.addWidget(self.add_page_button)
        self.verticalLayout_2.addWidget(self.tab_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalWidget_2.setSizePolicy(sizePolicy)
        self.verticalWidget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalWidget_21 = QtWidgets.QWidget(self.verticalWidget_2)
        self.verticalWidget_21.setStyleSheet("")
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_21)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.legend_widget = QtWidgets.QWidget(self.verticalWidget_21)
        self.legend_widget.setStyleSheet("")
        self.legend_widget.setObjectName("legend_widget")
        self.widget_4 = QtWidgets.QWidget(self.legend_widget)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 200, 290))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.line_settings_widget = QtWidgets.QWidget(self.widget_4)
        self.line_settings_widget.setGeometry(QtCore.QRect(0, 0, 200, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_settings_widget.sizePolicy().hasHeightForWidth())
        self.line_settings_widget.setSizePolicy(sizePolicy)
        self.line_settings_widget.setObjectName("line_settings_widget")
        self.label_7 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_7.setGeometry(QtCore.QRect(10, 235, 70, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_8.setGeometry(QtCore.QRect(10, 185, 70, 20))
        self.label_8.setObjectName("label_8")
        self.display_line_checkbox = QtWidgets.QCheckBox(self.line_settings_widget)
        self.display_line_checkbox.setGeometry(QtCore.QRect(170, 235, 20, 18))
        self.display_line_checkbox.setText("")
        self.display_line_checkbox.setChecked(True)
        self.display_line_checkbox.setObjectName("display_line_checkbox")
        self.line_colour_label = QtWidgets.QLabel(self.line_settings_widget)
        self.line_colour_label.setGeometry(QtCore.QRect(80, 160, 50, 20))
        self.line_colour_label.setStyleSheet("border: 1px solid #ddd;\n"
"background: #eee;")
        self.line_colour_label.setText("")
        self.line_colour_label.setObjectName("line_colour_label")
        self.line_pattern_label = QtWidgets.QLabel(self.line_settings_widget)
        self.line_pattern_label.setGeometry(QtCore.QRect(140, 160, 50, 20))
        self.line_pattern_label.setStyleSheet("border: 1px solid #ddd;\n"
"background: #eee;")
        self.line_pattern_label.setText("")
        self.line_pattern_label.setObjectName("line_pattern_label")
        self.line_width_slider = QtWidgets.QSlider(self.line_settings_widget)
        self.line_width_slider.setGeometry(QtCore.QRect(80, 185, 110, 22))
        self.line_width_slider.setMinimum(10)
        self.line_width_slider.setMaximum(100)
        self.line_width_slider.setSingleStep(5)
        self.line_width_slider.setProperty("value", 15)
        self.line_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_width_slider.setObjectName("line_width_slider")
        self.label_2 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 70, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_4.setGeometry(QtCore.QRect(10, 85, 70, 20))
        self.label_4.setObjectName("label_4")
        self.x_key_combo_box = QtWidgets.QComboBox(self.line_settings_widget)
        self.x_key_combo_box.setGeometry(QtCore.QRect(80, 85, 110, 20))
        self.x_key_combo_box.setObjectName("x_key_combo_box")
        self.label_3 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 70, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 70, 20))
        self.label_5.setObjectName("label_5")
        self.y_key_combo_box = QtWidgets.QComboBox(self.line_settings_widget)
        self.y_key_combo_box.setGeometry(QtCore.QRect(80, 110, 110, 20))
        self.y_key_combo_box.setObjectName("y_key_combo_box")
        self.label_6 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 70, 20))
        self.label_6.setObjectName("label_6")
        self.name_input = QtWidgets.QLineEdit(self.line_settings_widget)
        self.name_input.setGeometry(QtCore.QRect(80, 35, 110, 21))
        self.name_input.setObjectName("name_input")
        self.dataset_combo_box = QtWidgets.QComboBox(self.line_settings_widget)
        self.dataset_combo_box.setGeometry(QtCore.QRect(80, 60, 110, 20))
        self.dataset_combo_box.setObjectName("dataset_combo_box")
        self.label_9 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 70, 20))
        self.label_9.setObjectName("label_9")
        self.line_opacity_slider = QtWidgets.QSlider(self.line_settings_widget)
        self.line_opacity_slider.setGeometry(QtCore.QRect(80, 205, 110, 22))
        self.line_opacity_slider.setMinimum(0)
        self.line_opacity_slider.setMaximum(255)
        self.line_opacity_slider.setSingleStep(5)
        self.line_opacity_slider.setProperty("value", 250)
        self.line_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_opacity_slider.setObjectName("line_opacity_slider")
        self.remove_line_button = QtWidgets.QPushButton(self.line_settings_widget)
        self.remove_line_button.setGeometry(QtCore.QRect(145, 0, 26, 26))
        self.remove_line_button.setObjectName("remove_line_button")
        self.line_combo_box_3 = QtWidgets.QComboBox(self.line_settings_widget)
        self.line_combo_box_3.setGeometry(QtCore.QRect(0, 0, 140, 26))
        self.line_combo_box_3.setObjectName("line_combo_box_3")
        self.add_line_button = QtWidgets.QPushButton(self.line_settings_widget)
        self.add_line_button.setGeometry(QtCore.QRect(175, 0, 25, 25))
        self.add_line_button.setObjectName("add_line_button")
        self.label_10 = QtWidgets.QLabel(self.line_settings_widget)
        self.label_10.setGeometry(QtCore.QRect(10, 135, 100, 20))
        self.label_10.setObjectName("label_10")
        self.sort_by_x_checkbox = QtWidgets.QCheckBox(self.line_settings_widget)
        self.sort_by_x_checkbox.setGeometry(QtCore.QRect(170, 135, 20, 18))
        self.sort_by_x_checkbox.setText("")
        self.sort_by_x_checkbox.setChecked(True)
        self.sort_by_x_checkbox.setObjectName("sort_by_x_checkbox")
        self.label_7.raise_()
        self.label_8.raise_()
        self.display_line_checkbox.raise_()
        self.line_colour_label.raise_()
        self.line_pattern_label.raise_()
        self.line_width_slider.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.x_key_combo_box.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.y_key_combo_box.raise_()
        self.label_6.raise_()
        self.name_input.raise_()
        self.dataset_combo_box.raise_()
        self.label_9.raise_()
        self.line_opacity_slider.raise_()
        self.line_combo_box_3.raise_()
        self.remove_line_button.raise_()
        self.add_line_button.raise_()
        self.label_10.raise_()
        self.sort_by_x_checkbox.raise_()
        self.verticalLayout_5.addWidget(self.legend_widget)
        self.widget_3 = QtWidgets.QWidget(self.verticalWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_3.setStyleSheet("border: 1px solid #ccc;\n"
"background: #eee;")
        self.widget_3.setObjectName("widget_3")
        self.line_count_label = QtWidgets.QLabel(self.widget_3)
        self.line_count_label.setGeometry(QtCore.QRect(0, 0, 200, 20))
        self.line_count_label.setObjectName("line_count_label")
        self.edit_lines_button = QtWidgets.QPushButton(self.widget_3)
        self.edit_lines_button.setGeometry(QtCore.QRect(180, 0, 20, 20))
        font = QtGui.QFont()
        font.setFamily("OpenSansEmoji")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_lines_button.setFont(font)
        self.edit_lines_button.setObjectName("edit_lines_button")
        self.add_line_button_2 = QtWidgets.QPushButton(self.widget_3)
        self.add_line_button_2.setGeometry(QtCore.QRect(160, 0, 20, 20))
        self.add_line_button_2.setObjectName("add_line_button_2")
        self.verticalLayout_5.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.verticalWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget.setStyleSheet("border: 1px solid #ccc;\n"
"background: #eee;")
        self.widget.setObjectName("widget")
        self.add_dataset_button_3 = QtWidgets.QPushButton(self.widget)
        self.add_dataset_button_3.setGeometry(QtCore.QRect(160, 0, 20, 20))
        self.add_dataset_button_3.setObjectName("add_dataset_button_3")
        self.dataset_count_label = QtWidgets.QLabel(self.widget)
        self.dataset_count_label.setGeometry(QtCore.QRect(0, 0, 200, 20))
        self.dataset_count_label.setObjectName("dataset_count_label")
        self.edit_datasets_button = QtWidgets.QPushButton(self.widget)
        self.edit_datasets_button.setGeometry(QtCore.QRect(180, 0, 20, 20))
        font = QtGui.QFont()
        font.setFamily("OpenSansEmoji")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_datasets_button.setFont(font)
        self.edit_datasets_button.setObjectName("edit_datasets_button")
        self.dataset_count_label.raise_()
        self.edit_datasets_button.raise_()
        self.add_dataset_button_3.raise_()
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.verticalWidget_21)
        self.horizontalLayout.addWidget(self.verticalWidget_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chart_label = QtWidgets.QLabel(self.centralwidget)
        self.chart_label.setStyleSheet("background: #fff;")
        self.chart_label.setText("")
        self.chart_label.setObjectName("chart_label")
        self.verticalLayout.addWidget(self.chart_label)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(0, 40))
        self.widget1.setStyleSheet("border-top: 1px solid #ddd;")
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.home_button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setMaximumSize(QtCore.QSize(30, 30))
        self.home_button.setAutoFillBackground(False)
        self.home_button.setStyleSheet("border: 1px solid #ccc; border-radius: 2px;")
        self.home_button.setObjectName("home_button")
        self.horizontalLayout_4.addWidget(self.home_button)
        self.zoom_button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_button.sizePolicy().hasHeightForWidth())
        self.zoom_button.setSizePolicy(sizePolicy)
        self.zoom_button.setMaximumSize(QtCore.QSize(30, 30))
        self.zoom_button.setStyleSheet("border: 1px solid #ccc; border-radius: 2px;")
        self.zoom_button.setObjectName("zoom_button")
        self.horizontalLayout_4.addWidget(self.zoom_button)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setStyleSheet("border:none")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.screenshot_button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenshot_button.sizePolicy().hasHeightForWidth())
        self.screenshot_button.setSizePolicy(sizePolicy)
        self.screenshot_button.setMaximumSize(QtCore.QSize(30, 30))
        self.screenshot_button.setStyleSheet("border: 1px solid #ccc; border-radius: 2px;")
        self.screenshot_button.setObjectName("screenshot_button")
        self.horizontalLayout_4.addWidget(self.screenshot_button)
        self.verticalLayout.addWidget(self.widget1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        PlotterMainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(PlotterMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuData = QtWidgets.QMenu(self.menuBar)
        self.menuData.setObjectName("menuData")
        self.menuPage = QtWidgets.QMenu(self.menuBar)
        self.menuPage.setObjectName("menuPage")
        PlotterMainWindow.setMenuBar(self.menuBar)
        self.actionOpen_CSV = QtWidgets.QAction(PlotterMainWindow)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.add_file_action = QtWidgets.QAction(PlotterMainWindow)
        self.add_file_action.setObjectName("add_file_action")
        self.add_page_action = QtWidgets.QAction(PlotterMainWindow)
        self.add_page_action.setObjectName("add_page_action")
        self.delete_current_page_action = QtWidgets.QAction(PlotterMainWindow)
        self.delete_current_page_action.setObjectName("delete_current_page_action")
        self.edit_page_name_action = QtWidgets.QAction(PlotterMainWindow)
        self.edit_page_name_action.setObjectName("edit_page_name_action")
        self.menuData.addAction(self.add_file_action)
        self.menuPage.addAction(self.add_page_action)
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.edit_page_name_action)
        self.menuPage.addAction(self.delete_current_page_action)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuData.menuAction())
        self.menuBar.addAction(self.menuPage.menuAction())

        self.retranslateUi(PlotterMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotterMainWindow)

    def retranslateUi(self, PlotterMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotterMainWindow.setWindowTitle(_translate("PlotterMainWindow", "Plotter"))
        self.add_page_button.setText(_translate("PlotterMainWindow", "+"))
        self.label_7.setText(_translate("PlotterMainWindow", "Display:"))
        self.label_8.setText(_translate("PlotterMainWindow", "Line Width:"))
        self.label_2.setText(_translate("PlotterMainWindow", "Name:"))
        self.label_4.setText(_translate("PlotterMainWindow", "X Key:"))
        self.label_3.setText(_translate("PlotterMainWindow", "Dataset:"))
        self.label_5.setText(_translate("PlotterMainWindow", "Y Key:"))
        self.label_6.setText(_translate("PlotterMainWindow", "Line:"))
        self.label_9.setText(_translate("PlotterMainWindow", "Opacity"))
        self.remove_line_button.setText(_translate("PlotterMainWindow", "-"))
        self.add_line_button.setText(_translate("PlotterMainWindow", "+"))
        self.label_10.setText(_translate("PlotterMainWindow", "Sort By X Key:"))
        self.line_count_label.setText(_translate("PlotterMainWindow", "4 Lines"))
        self.edit_lines_button.setText(_translate("PlotterMainWindow", "📝"))
        self.add_line_button_2.setText(_translate("PlotterMainWindow", "+"))
        self.add_dataset_button_3.setText(_translate("PlotterMainWindow", "+"))
        self.dataset_count_label.setText(_translate("PlotterMainWindow", "4 Datasets"))
        self.edit_datasets_button.setText(_translate("PlotterMainWindow", "📝"))
        self.home_button.setToolTip(_translate("PlotterMainWindow", "Home (h)"))
        self.home_button.setText(_translate("PlotterMainWindow", "🏠"))
        self.zoom_button.setToolTip(_translate("PlotterMainWindow", "Zoom (z)"))
        self.zoom_button.setText(_translate("PlotterMainWindow", "🔍"))
        self.screenshot_button.setToolTip(_translate("PlotterMainWindow", "Screenshot (s)"))
        self.screenshot_button.setText(_translate("PlotterMainWindow", "📷"))
        self.menuFile.setTitle(_translate("PlotterMainWindow", "File"))
        self.menuData.setTitle(_translate("PlotterMainWindow", "Data"))
        self.menuPage.setTitle(_translate("PlotterMainWindow", "Pages"))
        self.actionOpen_CSV.setText(_translate("PlotterMainWindow", "Open CSV"))
        self.add_file_action.setText(_translate("PlotterMainWindow", "Add File"))
        self.add_page_action.setText(_translate("PlotterMainWindow", "Add page"))
        self.delete_current_page_action.setText(_translate("PlotterMainWindow", "Delete Current Page"))
        self.edit_page_name_action.setText(_translate("PlotterMainWindow", "Edit Page Name"))

