# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/StyleSelectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SelectStyleDialog(object):
    def setupUi(self, SelectStyleDialog):
        SelectStyleDialog.setObjectName("SelectStyleDialog")
        SelectStyleDialog.resize(166, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SelectStyleDialog.sizePolicy().hasHeightForWidth())
        SelectStyleDialog.setSizePolicy(sizePolicy)
        SelectStyleDialog.setMinimumSize(QtCore.QSize(166, 0))
        SelectStyleDialog.setMaximumSize(QtCore.QSize(166, 146))
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectStyleDialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(SelectStyleDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_preview_label = QtWidgets.QLabel(self.widget_3)
        self.line_preview_label.setStyleSheet("border: 1px solid #ddd;\n"
"background: #fff;")
        self.line_preview_label.setText("")
        self.line_preview_label.setObjectName("line_preview_label")
        self.gridLayout.addWidget(self.line_preview_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.style_combo_box = QtWidgets.QComboBox(SelectStyleDialog)
        self.style_combo_box.setObjectName("style_combo_box")
        self.verticalLayout.addWidget(self.style_combo_box)
        self.custom_pattern_widget = QtWidgets.QWidget(SelectStyleDialog)
        self.custom_pattern_widget.setObjectName("custom_pattern_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.custom_pattern_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.custom_pattern_widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.custom_pattern_input = QtWidgets.QLineEdit(self.custom_pattern_widget)
        self.custom_pattern_input.setObjectName("custom_pattern_input")
        self.verticalLayout_2.addWidget(self.custom_pattern_input)
        self.verticalLayout.addWidget(self.custom_pattern_widget)
        self.widget_2 = QtWidgets.QWidget(SelectStyleDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.done_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_button.sizePolicy().hasHeightForWidth())
        self.done_button.setSizePolicy(sizePolicy)
        self.done_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.done_button.setObjectName("done_button")
        self.horizontalLayout.addWidget(self.done_button)
        self.cancel_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(SelectStyleDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectStyleDialog)

    def retranslateUi(self, SelectStyleDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectStyleDialog.setWindowTitle(_translate("SelectStyleDialog", "Select Style"))
        self.label_3.setText(_translate("SelectStyleDialog", "Pattern:"))
        self.done_button.setText(_translate("SelectStyleDialog", "Done"))
        self.cancel_button.setText(_translate("SelectStyleDialog", "Cancel"))

